image:
  file: .gitpod/Dockerfile
tasks:
  - name: Setup KubeConfig
    command: mkdir -p ~/.kube && curl https://gist.githubusercontent.com/mattstratton/57768f4e1678d0453f845c437cc0b616/raw/45bd5ec1d214380d496656484c31d3e17947bd79/config -o ~/.kube/config
  - name: Start Docker Daemon
    command: sudo docker-up &
  - before: "echo 'export PIP_USER=no' >> ~/.bashrc && export PIP_USER=no"
    name: Use Pulumi
    command: pulumi login
ports:
  - port: 5000
    onOpen: ignore
vscode:
  extensions:
    - ms-python.python@2020.10.332292344:5ctthQ25Qni5/aAuOIUTYQ==
    - kevinrose.vsc-python-indent@1.12.0:NOHaOm1IToFrG4fit4+hUw==
    - magicstack.magicpython@1.1.1:Q+4h8/d9eu9kME/nNfIDlg==
    - robole.marky-markdown@2.7.0:2U+QLvBKB2yBSqNexOeyJg==
